"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.subscriptionRoutes = void 0;
const express_1 = require("express");
const SubscriptionController_1 = require("../../controllers/SubscriptionController");
const authMiddleware_1 = require("../../middlewares/authMiddleware");
const subscriptionRoutes = (0, express_1.Router)();
exports.subscriptionRoutes = subscriptionRoutes;
const subscriptionController = new SubscriptionController_1.SubscriptionController();
subscriptionRoutes.use(authMiddleware_1.authMiddleware);
subscriptionRoutes.post('/subscription', (req, res, next) => subscriptionController.createSubscription(req, res).catch(next));
subscriptionRoutes.patch('/subscription', (req, res, next) => subscriptionController.updateSubscription(req, res).catch(next));
subscriptionRoutes.get('/subscriptions', (req, res, next) => subscriptionController.getAllSubscriptions(req, res).catch(next));
